In [8]:
pip install pandas

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/4a/f6/f620ca62365d83e663a255a41b08d2fc2eaf304e0b8b21bb6d62a7390fe3/pandas-2.0.3-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Downloading pandas-2.0.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (18 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/ogbeks/Library/Python/3.10/lib/python/site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting tzdata>=2022.1 (from pandas)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Collecting numpy>=1.21.0 (from pandas)
  Obtaining dependency information for numpy>=1.21.0 from https://files.pythonhosted.org/packages/c3/ea/1d95b399078ecaa7b5d791e1fdbb3aee272077d9fd5fb499593c87dec5ea/numpy-1.25.2-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Downloading numpy-1.25.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (5.6 kB)
Requirement already satisfied: six>=1.5 in /Users/ogbeks/Library/Python/3.10/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.0.3-cp310-cp310-macosx_11_0_arm64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 353.1 kB/s eta 0:00:0000:0100:01
Downloading numpy-1.25.2-cp310-cp310-macosx_11_0_arm64.whl (14.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 371.9 kB/s eta 0:00:0000:0100:01
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-1.25.2 pandas-2.0.3 pytz-2023.3 tzdata-2023.3
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd
import numpy as np
import csv
from datetime import datetime as dt

In [10]:
df = pd.read_csv("iot_telemetry_data.csv")
df.head()

,ts,device,co,humidity,light,lpg,motion,smoke,temp
0,1.594512e+09,b8:27:eb:bf:9d:51,0.004956,51.000000,False,0.007651,False,0.020411,22.700000
1,1.594512e+09,00:0f:00:70:91:0a,0.002840,76.000000,False,0.005114,False,0.013275,19.700001
2,1.594512e+09,b8:27:eb:bf:9d:51,0.004976,50.900000,False,0.007673,False,0.020475,22.600000
3,1.594512e+09,1c:bf:ce:15:ec:4d,0.004403,76.800003,True,0.007023,False,0.018628,27.000000
4,1.594512e+09,b8:27:eb:bf:9d:51,0.004967,50.900000,False,0.007664,False,0.020448,22.600000

In [11]:
df['ts'] = pd.to_datetime(df['ts'], unit='s').dt.strftime("%Y-%m-%dT%H:%M:%S.%f+0000")
df.head(5)

,ts,device,co,humidity,light,lpg,motion,smoke,temp
0,2020-07-12T00:01:34.385974+0000,b8:27:eb:bf:9d:51,0.004956,51.000000,False,0.007651,False,0.020411,22.700000
1,2020-07-12T00:01:34.735567+0000,00:0f:00:70:91:0a,0.002840,76.000000,False,0.005114,False,0.013275,19.700001
2,2020-07-12T00:01:38.073572+0000,b8:27:eb:bf:9d:51,0.004976,50.900000,False,0.007673,False,0.020475,22.600000
3,2020-07-12T00:01:39.589145+0000,1c:bf:ce:15:ec:4d,0.004403,76.800003,True,0.007023,False,0.018628,27.000000
4,2020-07-12T00:01:41.761234+0000,b8:27:eb:bf:9d:51,0.004967,50.900000,False,0.007664,False,0.020448,22.600000

In [17]:
dfs = dict(tuple(df.groupby('device')))

In [15]:
df['device'].unique()

array(['b8:27:eb:bf:9d:51', '00:0f:00:70:91:0a', '1c:bf:ce:15:ec:4d'],
      dtype=object)

In [18]:
device1= dfs['b8:27:eb:bf:9d:51']
device1=device1.drop('device', axis=1)
device1.head()

,ts,co,humidity,light,lpg,motion,smoke,temp
0,2020-07-12T00:01:34.385974+0000,0.004956,51.0,False,0.007651,False,0.020411,22.7
2,2020-07-12T00:01:38.073572+0000,0.004976,50.9,False,0.007673,False,0.020475,22.6
4,2020-07-12T00:01:41.761234+0000,0.004967,50.9,False,0.007664,False,0.020448,22.6
6,2020-07-12T00:01:45.448863+0000,0.004976,50.9,False,0.007673,False,0.020475,22.6
9,2020-07-12T00:01:49.136686+0000,0.004970,50.9,False,0.007667,False,0.020457,22.6

In [19]:
device2= dfs['00:0f:00:70:91:0a']
device2=device2.drop('device', axis=1)
device2.head()

,ts,co,humidity,light,lpg,motion,smoke,temp
1,2020-07-12T00:01:34.735567+0000,0.002840,76.000000,False,0.005114,False,0.013275,19.700001
7,2020-07-12T00:01:46.869075+0000,0.002938,76.000000,False,0.005241,False,0.013628,19.700001
15,2020-07-12T00:02:02.785731+0000,0.002905,75.800003,False,0.005199,False,0.013509,19.700001
20,2020-07-12T00:02:11.476376+0000,0.002938,75.800003,False,0.005241,False,0.013628,19.700001
23,2020-07-12T00:02:15.289086+0000,0.002840,76.000000,False,0.005114,False,0.013275,19.700001

In [20]:
device3= dfs['1c:bf:ce:15:ec:4d']
device3=device3.drop('device', axis=1)
device3.head()

,ts,co,humidity,light,lpg,motion,smoke,temp
3,2020-07-12T00:01:39.589145+0000,0.004403,76.800003,True,0.007023,False,0.018628,27.0
5,2020-07-12T00:01:44.468410+0000,0.004391,77.900002,True,0.007009,False,0.018589,27.0
8,2020-07-12T00:01:48.275381+0000,0.004345,77.900002,True,0.006957,False,0.018440,27.0
11,2020-07-12T00:01:55.288542+0000,0.004383,78.000000,True,0.007000,False,0.018563,27.0
13,2020-07-12T00:01:59.098013+0000,0.004451,78.000000,True,0.007079,False,0.018786,27.0

In [21]:
device1.to_csv('device1.csv', encoding='utf-8', quotechar='"', index=False, quoting=csv.QUOTE_ALL)

In [22]:
device2.to_csv('device2.csv', encoding='utf-8', quotechar='"', index=False, quoting=csv.QUOTE_ALL)

In [23]:
device3.to_csv('device3.csv', encoding='utf-8', quotechar='"', index=False, quoting=csv.QUOTE_ALL)

In [26]:
device1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 187451 entries, 0 to 405183
Data columns (total 8 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   ts        187451 non-null  object
 1   co        187451 non-null  float64
 2   humidity  187451 non-null  float64
 3   light     187451 non-null  bool
 4   lpg       187451 non-null  float64
 5   motion    187451 non-null  bool
 6   smoke     187451 non-null  float64
 7   temp      187451 non-null  float64
dtypes: bool(2), float64(5), object(1)
memory usage: 10.4+ MB

In [36]:
metadata={
  "version":"5.3.0",
  "database":"public",
  "container":"device1",
  "containerType":"TIME_SERIES",
  "containerFileType":"csv",
  "containerFile": "public.device1.csv",
  "columnSet":[],
  "rowKeySet":["ts"],
  "timeSeriesProperties":{
    "compresssionMethod":"NO",
    "compressionWindowSize":-1,
    "compressionWindowSizeUnit":"null",
    "expirationDivisionCount":-1,
    "rowExpirationElapsedTime":-1,
    "rowExpirationTimeUnit":"null"
  },
  "compressionInfoSet":[]
}

In [37]:
def generate_schema(dataframe) -> list:
    schema = []
    for column_name, dtype in dataframe.dtypes.items():
      if column_name == 'ts':
          field_type='timestamp'
      elif dtype == 'int64':
          field_type = 'INTEGER'
      elif dtype == 'float64':
          field_type = 'double'
      elif dtype == 'bool':
          field_type = 'bool'
      elif dtype == 'datetime64':
          field_type = 'timestamp'
      else:
          field_type = 'STRING'
      if dtype=='object':
        is_nullable=True
      else:
        is_nullable=False
      schema.append({
          'columnName': column_name,
          'type': field_type,
          'notNull': is_nullable
      })
    return schema

In [32]:
generate_schema(device1)

[{'columnName': 'ts', 'type': 'timestamp', 'notNull': True},
 {'columnName': 'co', 'type': 'double', 'notNull': False},
 {'columnName': 'humidity', 'type': 'double', 'notNull': False},
 {'columnName': 'light', 'type': 'bool', 'notNull': False},
 {'columnName': 'lpg', 'type': 'double', 'notNull': False},
 {'columnName': 'motion', 'type': 'bool', 'notNull': False},
 {'columnName': 'smoke', 'type': 'double', 'notNull': False},
 {'columnName': 'temp', 'type': 'double', 'notNull': False}]

In [38]:
metadata['columnSet'] = generate_schema(device1)

In [34]:
import json

In [39]:
with open('public.device1_properties.json', 'w') as json_file:
  json.dump(metadata, json_file, indent=4)